WebCoreUI/Controllers/CallController.cs
using Business.Abstract;
using Entities.Concrete;
using Entities.DTOs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient.Server;
using Newtonsoft.Json;
using System.Runtime.CompilerServices;
using System.Security.Claims;
using Core.Utilities.Helpers;

namespace WebCoreUI.Controllers
{
    [Route("Call/CallCreate/")]
    public class CallController : Controller
    {
        ICallService _callService;

        public CallController(ICallService callService)
        {
            _callService = callService;
        }
        
        [HttpGet]
        [Route("{requestId?}/{customerId?}")]
        public IActionResult CallCreate(int requestId,int customerId)
        {
            CallDto callDto = new CallDto();

            ViewBag.RequestId = requestId;
            ViewBag.CustomerId = customerId;
          
            return View(callDto);
        }

        [HttpPost]
        [Route("{requestId?}/{customerId?}")]
        public IActionResult CallCreate(CallDto model)
        {
            ModelState.Remove("CallId");            
            ModelState.Remove("CustomerRepId");
            if (ModelState.IsValid)
            {           
                string emailForClaim = User.FindFirstValue("Email");

                _callService.AddCallDto(model, emailForClaim);

                string email = _callService.CallwithCustomer(model.CustomerId);

                //Müşteriye otomatik olarak görüşme bilgilendirme Maili gönderme
                EmailToInformation emailHelper = new EmailToInformation();
                emailHelper.SendEmail(email);

                return Redirect("/CustomerRep/ProfileCustRep");

            }
            return View(model);
 
        }     
    }
}

WebCoreUI/Controllers/RequestController.cs
using Business.Abstract;
using Entities.Concrete;
using Entities.DTOs;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace WebCoreUI.Controllers
{
    public class RequestController : Controller
    {
        IRequestService _requestService;

        public RequestController(IRequestService requestService)
        {
            _requestService = requestService;
        }

        public IActionResult Index()
        {
            return View();
        }

        //Hangi müşteri login olduysa onun Taleplerini gösteren method
        public IActionResult RequestListByCustomerId()
        {
            string emailForClaim = User.FindFirstValue("Email");   
            var response = _requestService.GetRequestByEmail(emailForClaim);

            return View(response);
        }

        //Talep Ekleme Form Ekranı
        public IActionResult RequestCreate()
        {
            ViewBag.RequestTypes = _requestService.GetBySelectListRequestTypes();
            return View("RequestCreateForm", new RequestCreateDto());
        }
        [HttpPost]
        public IActionResult RequestCreate(RequestCreateDto model)
        {
            //Claimdeki Id : 
            int customerId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            
            _requestService.AddRequestCreateDto(model,customerId);
            return RedirectToAction(nameof(RequestListByCustomerId));
        }

        //Bütün Taleplerin Listesi
        public IActionResult RequestList()
        {
            var response = _requestService.GetAllRequestList();
            return View(response);
        }

        //Müşteri Temsilcisinin Talebi Aldığı Method
        //Talep Detay sayfasına geçer 
        public IActionResult RequestCheckByCustomerRep(int requestId)
        {
            string emailForClaim = User.FindFirstValue("Email");
            ViewBag.RequestId = requestId;

            var response = _requestService.RequestDetailByCustomerRep(requestId, emailForClaim);
            return View("RequestDetailForm", response);
           
        }
       
        //Kapanan Talepleri Listeleyen method
         public IActionResult RequestCompletedList()
        {
            var response = _requestService.GetRequestCompletedList();
            return View(response);
        }

        //Yeni açılan Talepleri Listeleyen method
        public IActionResult RequestNewList()
        {
            var response = _requestService.GetRequestNewList();
            return View(response);
        }

        //Değerlendirmede olan Talepleri Listeleyen method
        public IActionResult RequestContinueList()
        {
            var response = _requestService.GetRequestContinueList();
            return View(response);
        }

       
        //Müşteri Temsilcisinin çözdüğü Taleplerin Listesi
        public IActionResult CustomerRepRequestCompletedList()
        {
            string emailForClaim = User.FindFirstValue("Email");
            ViewBag.CustomerRepEmail=emailForClaim;
            var response = _requestService.GetCustomerRepRequestCompletedList(emailForClaim);
            return View(response);
        }

    }
}

WebCoreUI/Views/Request/CustomerRepRequestCompletedList.cshtml
@model List<Entities.DTOs.CustomerRepRequestCompletedListDto>

@{
    ViewData["Title"] ="Kullanıcılı Müşteri Temsilcisinin Çözdüğü Talepler";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row mt-3 mb-3">
        <div class="col-12 text-center">
            <h1 class="display-4"> @ViewBag.CustomerRepEmail @ViewData["Title"]</h1>
        </div>
    </div>


    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Müşteri</th>
                                <th>Talep Tarihi</th>
                                <th>Talep</th>
                                <th>Talep Türü</th>
                                <th>Durum</th>
                                <th>Müşteri Temsilcisi</th>
                               
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.CustomerName</td>
                                    <td>@item.CreateDate.ToString("dd MMMM yyyy")</td>
                                    <td>@item.Description</td>
                                    <td>@item.RequestTypeName</td>
                                    <td>@item.StatusName</td>
                                    <td>@item.CustomerRepName</td>
                                   
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

WebCoreUI/Views/Request/RequestCompletedList.cshtml
@model List<Entities.DTOs.RequestCompletedListDto>

@{
    ViewData["Title"] = "ÇÖZÜLMÜŞ TALEPLER";
}

<div class="container">
    <div class="row mt-3 mb-3">
        <div class="col-12 text-center">
            <h1 class="display-4">@ViewData["Title"]</h1>
        </div>
    </div>


    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Müşteri</th>
                                <th>Talep Tarihi</th>
                                <th>Talep</th>
                                <th>Talep Türü</th>
                                <th>Durum</th>
                                <th>Müşteri Temsilcisi</th>
                                <th>  </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.CustomerName</td>
                                    <td>@item.CreateDate.ToString("dd MMMM yyyy")</td>
                                    <td>@item.Description</td>
                                    <td>@item.RequestTypeName</td>
                                    <td>@item.StatusName</td>
                                    <td>@item.CustomerRepName</td>
                                    <td>
                                        <a asp-action="RequestCheckByCustomerRep" asp-controller="Request" asp-route-requestId="@item.RequestId" class="btn btn-primary"><i class="fa-solid fa-folder-plus"></i> Talebi Al</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

WebCoreUI/Views/Request/RequestContinueList.cshtml
@model List<Entities.DTOs.RequestContinueListDto>

@{
    ViewData["Title"] = "DEĞERLENDİRMEDE OLAN TALEPLER";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row mt-3 mb-3">
        <div class="col-12 text-center">
            <h1 class="display-4">@ViewData["Title"]</h1>
        </div>
    </div>


    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Müşteri</th>
                                <th>Talep Tarihi</th>
                                <th>Talep</th>
                                <th>Talep Türü</th>
                                <th>Durum</th>
                                <th>Müşteri Temsilcisi</th>
                               
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.CustomerName</td>
                                    <td>@item.CreateDate.ToString("dd MMMM yyyy")</td>
                                    <td>@item.Description</td>
                                    <td>@item.RequestTypeName</td>
                                    <td>@item.StatusName</td>
                                    <td>@item.CustomerRepName</td>
                                   @* <td>
                                        <a asp-action="RequestCheckByCustomerRep" asp-controller="Request" asp-route-requestId="@item.RequestId" class="btn btn-primary"><i class="fa-solid fa-folder-plus"></i> Talebi Al</a>
                                    </td>*@
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

WebCoreUI/Views/Request/RequestCreateForm.cshtml
@model Entities.DTOs.RequestCreateDto

@{
    ViewData["Title"] = "TALEP OLUŞTURMA";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-4 offset-4">
        <h1 class="display4 border-bottom text-center pb-2">Talep Formu</h1>
    </div>
</div>


<div class="card">
    <div class="card-body">
        <h5 class="card-title">Yeni Talep Oluştur</h5>
        <form asp-action="RequsetCreate" asp-controller="Request" data-val="true" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger small"></div>
            <div class="form-group mt-3">
                <label asp-for="RequestTypeId" class="form-label">Talep Türü</label>
                <select asp-for="RequestTypeId" name="RequestTypeId" asp-items="ViewBag.RequestTypes" class="form-select">
                    <option value="0">Talep Türü seçiniz</option>
                </select>
            </div>
            <div class="form-group mt-3">
                <label asp-for="Description" class="form-label">Taleplerinizi bizimle paylaşabilirsiniz</label>
                <textarea asp-for="Description" value="@Model.Description" class="form-control mb-3" rows="10" cols="30" placeholder="talebiniz..."></textarea>
                <span asp-validation-for="Description" class="text-danger small"></span>
            </div>
            <div class="d-grid">
                <button class="btn btn-primary" asp-route-id="@ViewBag.RequestTypeId" type="submit"><i class="fa-solid fa-floppy-disk me-2"></i>Kaydet</button>
            </div>
        </form>
    </div>
</div>

WebCoreUI/Views/Request/RequestDetailForm.cshtml
@model Entities.DTOs.RequestAllListDto

@{
    ViewData["Title"] = "TALEP DETAYLARI";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row mt-3 mb-3">
        <div class="col-12 text-center">
            <h1 class="display-4">@ViewData["Title"]</h1>
        </div>
    </div>


    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Müşteri</th>
                                <th>Talep Tarihi</th>
                                <th>Talep</th>
                                <th>Talep Türü</th>
                                <th>Durum</th>
                                <th>Müşteri Temsilcisi</th>
                                <th>  </th>
                            </tr>
                        </thead>
                        <tbody>
                            
                                <tr>
                                    <td>@Model.CustomerName</td>
                                    <td>@Model.CreateDate.ToString("dd MMMM yyyy")</td>
                                    <td>@Model.Description</td>
                                    <td>@Model.RequestTypeName</td>
                                    <td>@Model.StatusName</td>
                                    <td>@Model.CustomerRepName</td>
                                    <td>
                                    
                                        @*<a asp-action="CallCreate" asp-controller="Call" asp-route-requestId="@ViewBag.RequestId" class="btn btn-primary"><i class="fa-solid fa-phone-volume"></i> Talep Görüşme</a>*@

                                        <a class="btn btn-primary" href="/Call/CallCreate/@ViewBag.RequestId/@Model.CustomerId"> <i class="fa-solid fa-phone-volume"></i> Talep Görüşme </a>

                                    </td>
                                </tr>
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

WebCoreUI/Views/Request/RequestList.cshtml
@model List<Entities.DTOs.RequestAllListDto>

@{
    ViewData["Title"] = "MÜŞTERİ TALEPLERİ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row mt-3 mb-3">
        <div class="col-12 text-center">
            <h1 class="display-4">@ViewData["Title"]</h1>
        </div>
    </div>

   
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>                              
                                <th>Müşteri</th>
                                <th>Talep Tarihi</th>
                                <th>Talep</th>
                                <th>Talep Türü</th>
                                <th>Durum</th>
                                <th>Müşteri Temsilcisi</th>
                                <th>  </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.CustomerName</td>
                                    <td>@item.CreateDate.ToString("dd MMMM yyyy")</td>
                                    <td>@item.Description</td>
                                    <td>@item.RequestTypeName</td>
                                    <td>@item.StatusName</td>
                                    <td>@item.CustomerRepName</td>
                                    <td>
                                        <a asp-action="RequestCheckByCustomerRep" asp-controller="Request" asp-route-requestId="@item.RequestId" class="btn btn-primary"><i class="fa-solid fa-folder-plus"></i> Talebi Al</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

WebCoreUI/Views/Request/RequestListByCustomerId.cshtml
@model List<Entities.DTOs.RequestListByCustomerDto>

@{
    ViewData["Title"] = "TALEPLERİM";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row mt-3 mb-3">
        <div class="col-12 text-center">
            <h1 class="display-4"> @ViewData["Title"]</h1>
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-12">
            <a asp-action="RequestCreate" asp-controller="Request" class="btn btn-primary">
                <i class="fa-sharp fa-solid fa-plus"></i>
                Talep Ekle
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Talep Tarihi</th>
                                <th>Talep</th>
                                <th>Talep Türü</th>
                                <th>Durum</th>
                                <th>Müşteri Temsilcisi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.CreateDate.ToString("dd MMMM yyyy")</td>
                                    <td>@item.Description</td>
                                    <td>@item.RequestTypeName</td>
                                    <td>@item.StatusName</td>
                                    <td>@item.CustomerRepName</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

WebCoreUI/Views/Request/RequestNewList.cshtml
@model List<Entities.DTOs.RequestNewListDto>

@{
    ViewData["Title"] = "YENİ AÇILAN TALEPLER";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row mt-3 mb-3">
        <div class="col-12 text-center">
            <h1 class="display-4">@ViewData["Title"]</h1>
        </div>
    </div>


    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Müşteri</th>
                                <th>Talep Tarihi</th>
                                <th>Talep</th>
                                <th>Talep Türü</th>
                                <th>Durum</th>
                                <th>Müşteri Temsilcisi</th>
                                <th>  </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.CustomerName</td>
                                    <td>@item.CreateDate.ToString("dd MMMM yyyy")</td>
                                    <td>@item.Description</td>
                                    <td>@item.RequestTypeName</td>
                                    <td>@item.StatusName</td>
                                    <td>@item.CustomerRepName</td>
                                    <td>
                                        <a asp-action="RequestCheckByCustomerRep" asp-controller="Request" asp-route-requestId="@item.RequestId" class="btn btn-primary"><i class="fa-solid fa-folder-plus"></i> Talebi Al</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>