WebCoreUI/Controllers/AdminController.cs
using Business.Abstract;
using Entities.Concrete;
using Entities.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Plugins;
using System.Collections.Generic;
using System.Security.Claims;

namespace WebCoreUI.Controllers
{
    [Authorize(Roles = "admin")]
    [Route("[controller]/[action]")]
    public class AdminController : Controller
    {
        IAdminService _adminService;

        public AdminController(IAdminService adminService)
        {
            _adminService = adminService;
        }

        // AdminLayout.cshtml      
        [HttpGet]
        public IActionResult AdminIndex()
        {
            return View();
        }

        //Admin tarafta Müşteriler Listesi
        [HttpGet]
        public IActionResult GetAllCustomer()
        {
            var response = _adminService.GetAllCustomerList();
            return View(response);
        }

        //Admin tarafta Müşterinin Talepleri
        [HttpGet]
        public IActionResult GetRequestListByCustomerId(int customerId)
        {
            ViewBag.CustomerName = _adminService.GetByIdCustomerName(customerId);
            var response = _adminService.GetRequestsByCustomerId(customerId);
            return View(response);
        }

        //Admin tarafta Müşteririnin Taleplerini Asenkron getirme
        //[HttpGet]
        //public async Task<IActionResult> GetRequestListByCustomerIdAsync(int customerId)
        //{
        //    ViewBag.CustomerName = await _adminService.GetByIdCustomerNameAsync(customerId);
        //    var response = _adminService.GetRequestsByCustomerId(customerId);
        //    return View(response);

        //}


        //Admin tarafta MüşteriTemsilcilerini Listeleme
        [HttpGet]
        public IActionResult GetAllCustomerRep()
        {
            var response = _adminService.GetAllCustomerRepList();
            return View(response);
        }

        //Müşteri Temsilcisi Kayıt Ekran Formu
        [AllowAnonymous]
        public IActionResult CreateCustomerRep()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public IActionResult CreateCustomerRep(CustomerRepRegisterDto model)
        {
            if (ModelState.IsValid)
            {
                _adminService.AddCustomerRepDto(model);
                return RedirectToAction(nameof(GetAllCustomerRep));
            }

            ModelState.AddModelError("", "Üye olma işlemi gerçekleşmedi");
            return View(model);
        }

        [HttpGet]
        //[Route("{customerId?}/{customerRepId?}")]
        public IActionResult EditCustomerRep(int customerId)
        {
            CustomerRepEditDto model = _adminService.GetCustomerRepByCustomerId(customerId);

            //ViewBag.CustomerId = customerId;
            //ViewBag.CustomerRepId = customerRepId;

            return View(model);
        }
        [HttpPost]
        //[Route("{customerId?}/{customerRepId?}")]
        public IActionResult EditCustomerRep(CustomerRepEditDto model)
        {
            _adminService.EditCustomerRepDto(model);
            return RedirectToAction(nameof(GetAllCustomerRep));
        }

        [HttpGet]
        public IActionResult DeleteCustomerRep(int customerId)
        {
            _adminService.DeleteCustomerRepDto(customerId);
            return RedirectToAction(nameof(GetAllCustomerRep));
        }

        //Müşteri Temsilcisi Rapor Ekranı
        [HttpGet]
        public IActionResult GetReport()
        {
            ViewBag.AllCompletedRequest = _adminService.GetReportList()[0].AllCompletedRequestCount;
            ViewBag.AllCallTime = _adminService.GetReportList()[0].AllCallTimeTotal;

            return View(_adminService.GetReportList());
        }

        //Müşteri Temsilcisi Belli Tarih aralığındaki Rapor Ekranı
        public IActionResult GetReportByDate()
        {
            return View(new List<ReportByDateDto>());
        }

        //Müşteri Temsilcisi Belli Tarih aralığındaki Rapor Ekranı
        [HttpPost]
        public IActionResult GetReportByDate(DateTime startDate, DateTime endDate)
        {
            ViewBag.StartDate = startDate;  
            ViewBag.EndDate = endDate;
            ViewBag.AllCompletedRequest = _adminService.GetByDateReportList(startDate,endDate)[0].AllCompletedRequestCount;
            ViewBag.AllCallTime = _adminService.GetByDateReportList(startDate,endDate)[0].AllCallTimeTotal;
            var reportList = _adminService.GetByDateReportList(startDate, endDate);
            return View(reportList);
        }

      
    }
}

WebCoreUI/Controllers/CustomerController.cs
using Business.Abstract;
using DataAccess.Abstract;
using Entities.DTOs;
using System.Web;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Options;
using System.Security.Claims;
using Entities.Concrete;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ApiExplorer;

namespace WebCoreUI.Controllers
{
    // [Authorize(Roles ="customer")]
    public class CustomerController : Controller
    {
        ICustomerService _customerService;
        private readonly IHttpContextAccessor _httpContextAccessor;


        public CustomerController(ICustomerService customerService, IHttpContextAccessor httpContextAccessor)
        {
            _customerService = customerService;
            this._httpContextAccessor = httpContextAccessor;
        }
        //Müşteri Ekranı 
        public IActionResult ProfileCust()
        {
            return View();
        }

        //ÜyeOl Ekranı formu
        [AllowAnonymous]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public IActionResult Register(CustomerRegisterDto model)
        {
            if (ModelState.IsValid)
            {
                _customerService.AddCustomerDto(model);
                return RedirectToAction(nameof(Login));
            }

            ModelState.AddModelError("", "Üye olma işlemi gerçekleşmedi");
            return View(model);
        }

        //Giriş Ekranı formu
        [AllowAnonymous]
        public IActionResult Login()
        {
            return View();
        }

        #region JwtToken_LoginOlma
        //[HttpPost]
        //[AllowAnonymous]
        //public IActionResult Login(CustomerLoginDto model)
        //{
        //    //Mail ve şifre databasede var mı
        //    var customerdb = _customerService.GetByLoginFilter(model);

        //    if (customerdb == null)
        //    {
        //        return RedirectToAction(nameof(Login));
        //    }

        //    _httpContextAccessor.HttpContext.Response.Cookies.Append("token", customerdb.Token , new CookieOptions()
        //    {
        //        HttpOnly = true,
        //        Expires = DateTime.Now.AddDays(1),
        //        Secure = true,
        //        IsEssential = true,
        //        SameSite = SameSiteMode.None,
        //    }); // Oluştuyrulan tokeni cookie ye basmak için kullanılır 


        //    //eğer çağrı merkezi personeli ise // x viewine eğer müşteri ise y viewine redirect ediceksin 
        //    if (customerdb.Role == "customerRep")
        //    {
        //        return RedirectToAction("Index", "CustomerRep");

        //    }
        //    else
        //    {
        //        return RedirectToAction("Index", "Customer");
        //    }

        //} 
        #endregion


        [HttpPost]
        [AllowAnonymous]
        public IActionResult Login(CustomerLoginDto model)
        {
            ModelState.Remove("CustomerId");
            ModelState.Remove("Role");

            if (ModelState.IsValid)
            {
                try
                {
                    //Mail ve şifre eşleşiyor mu
                    var existCustomer = _customerService.GetByLoginFilter(model);
                    if (existCustomer == null)
                    {
                        return RedirectToAction(nameof(Login));
                    }

                    List<Claim> claims = new List<Claim>();
                    claims.Add(new Claim(ClaimTypes.NameIdentifier, existCustomer.CustomerId.ToString()));
                    claims.Add(new Claim("Email", existCustomer.Email));
                    claims.Add(new Claim("Password", existCustomer.Password));
                    claims.Add(new Claim(ClaimTypes.Role, existCustomer.Role));

                    ClaimsIdentity identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                    ClaimsPrincipal principal = new ClaimsPrincipal(identity);

                    HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                    ViewData["loginResult"] = "loginSuccess";
                    ViewData["loginMessage"] = "Giriş işlemi başarılı";
                }
                catch
                {
                    ViewData["loginResult"] = "loginError";
                    ViewData["loginMessage"] = "Giriş yapılamadı //Mail Parola eşleşmedi";

                }
               
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewData["loginResult"] = "loginError";
                ViewData["loginMessage"] = "Mail yada Parola boş geçilemez";
                return View(model);
            }
            
        }

        public IActionResult Logout()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);  //Cookieyi kapat
            return RedirectToAction(nameof(Login));
        }

        //Müşterinin Bilgi formunu CustomerId ye göre dolu getirme
        [HttpGet]
        public IActionResult CustomerInformation()
        {
            //Claimdeki Id : 
            int customerId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            CustomerInformationDto model = _customerService.GetCustomerInformation(customerId);
            return View(model);
        }

        //Müşteri Bilgileri Güncelleme
        [HttpPost]
        public IActionResult CustomerInformation(CustomerInformationDto model)
        {
            _customerService.GetCustomerInformationDto(model);
            return RedirectToAction(nameof(CustomerInformation));
        }

        //Müşterinin Bilgi formunu CustomerId ye göre dolu getirme
        [HttpGet]
        public IActionResult CustomerInformationProfile()
        {
            ProfileInfoLoader();
            return View();
        }

        private void ProfileInfoLoader()      //Açılışta değerleri dolu getiren metodumuz
        {
            //Claimdeki Id : 
            int customerId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            CustomerInformationDto model = _customerService.GetCustomerInformation(customerId);
            ViewData["FirstName"] = model.FirstName;
            ViewData["LastName"] = model.LastName;
            ViewData["Phone"] = model.Phone;
            ViewData["Email"] = model.Email;
            ViewData["Password"] = model.Password;
        }


        //Müşteri AdıSoyadı Güncelleme
        //Veriler model olmadan nasıl gelir? --Inputların (name="firstName") name içindeki ismini parametre olarak verebiliriz
        [HttpPost]
        public IActionResult ProfileChangeFullName([Required][MinLength(2)][StringLength(50)] string? firstName, [Required][StringLength(50)] string? lastName)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    //Claimdeki Id : 
                    int customerId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
                    _customerService.GetProfileChangeFullName(firstName, lastName, customerId);

                    ViewData["fullNameResult"] = "fullNameResultChange";
                    ProfileInfoLoader();
                }
                catch (Exception ex)
                {
                    ViewData["fullNameResult"] = "fullNameResultChangeFail";
                    ViewData["fullNameResultMessage"] = ex.Message.ToString();
                }

                return View(nameof(CustomerInformationProfile));
            }
            else
            {
                ViewData["fullNameResult"] = "fullNameResultChangeFail";
                ViewData["fullNameResultMessage"] = "Ad Alanı Boş";
                return View(nameof(CustomerInformationProfile));
            }
        }

        //Müşteri Telefon Güncelleme
        [HttpPost]
        public IActionResult ProfileChangePhone([Required] string? phone)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    //Claimdeki Id : 
                    int customerId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
                    _customerService.GetProfileChangePhone(phone, customerId);

                    ViewData["phoneResult"] = "PhoneChange";
                    ViewData["phoneResultMessage"] = "Telefon numarası değişdi";
                    ProfileInfoLoader();

                }
                catch
                {
                    ViewData["phoneResult"] = "PhoneChangeFail";
                    ViewData["phoneResultMessage"] = "Telefon numarası değişmedi";
                }
                return View(nameof(CustomerInformationProfile));
            }
            else
            {
                ViewData["phoneResult"] = "PhoneChangeFail";
                ViewData["phoneResultMessage"] = "Telefon numarası boş olamaz";
                return View(nameof(CustomerInformationProfile));
            }
        }

        //Müşteri Mail Güncelleme
        [HttpPost]
        public IActionResult ProfileChangeEmail([Required][EmailAddress] string? email)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    //Claimdeki Id : 
                    int customerId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
                    _customerService.GetProfileChangeEmail(email, customerId);

                    ViewData["emailResult"] = "EmailChange";
                    ViewData["emailResultMessage"] = "Mail adresi değişdi";
                    ProfileInfoLoader();

                }
                catch
                {

WebCoreUI/Controllers/CustomerRepController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebCoreUI.Controllers
{
    public class CustomerRepController : Controller
    {
       [Authorize(Roles ="customerRep")]  //login olmuş ve rolü=customerRep olanlar girebilir
        public IActionResult ProfileCustRep()
        {
            return View();
        }
    }
}

WebCoreUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebCoreUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/fontawesome.min.css" rel="stylesheet" />
    <link href="~/lib/fontawesome-iconpicker/css/fontawesome-iconpicker.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebCoreUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="AdminIndex">CallCenter Yönetim Paneli</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">




                        @if (User.Identity.IsAuthenticated) //User propertsindeki ıdentitye ulaşıp IsAuthenticated mi diye bakarız
                        {
                            @if
                           (User.IsInRole("customer"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="ProfileCust"><i class="fa-solid fa-user me-2"></i>@User.FindFirst("Email").Value</a>  @*Claimlerin içinde FindFirst ile "Email" claimini arıyor. Valuue ile değerini oku*@
                                </li>
                            }
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Logout"><i class="fa-solid fa-right-from-bracket me-2"></i>Çıkış Yap</a>
                            </li>

                        }
                        else
                        {

                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Login"><i class="fa-solid fa-right-to-bracket me-2"></i>Giriş Yap</a>
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Register"><i class="fa-solid fa-user me-2"></i>Üye Ol</a>
                            </li>
                        }


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="c:\users\ysnes\.nuget\packages\ntoastnotify\8.0.0\contentfiles\any\net6.0\wwwroot\noty.js"></script>
    <script src="c:\users\ysnes\.nuget\packages\ntoastnotify\8.0.0\contentfiles\any\net6.0\wwwroot\toastr.js"></script>
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebCoreUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebCoreUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
   
    <link href="~/lib/toastr.js/toastr.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/fontawesome.min.css" rel="stylesheet" />
    <link href="~/lib/fontawesome-iconpicker/css/fontawesome-iconpicker.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebCoreUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CallCenter</a>            
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">


                        @if (User.Identity.IsAuthenticated) //User propertsindeki ıdentitye ulaşıp IsAuthenticated mi diye bakarız
                        {
                            @if (User.IsInRole("customerRep"))
                            {
                                <li class="nav-item ">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="CustomerRep" asp-action="ProfileCustRep"><i class="fa-solid fa-user me-2"></i>Müşteri Temsilcisi</a>
                                </li>
                            }
                            @if(User.IsInRole("customer"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="ProfileCust"><i class="fa-solid fa-user me-2"></i>@User.FindFirst("Email").Value</a>  @*Claimlerin içinde FindFirst ile "Email" claimini arıyor. Valuue ile değerini oku*@
                                </li>
                            }
                            @if (User.IsInRole("admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="AdminIndex"><i class="fa-solid fa-user me-2"></i>ADMİN PANELİ</a>  @*Claimlerin içinde FindFirst ile "Email" claimini arıyor. Valuue ile değerini oku*@
                                </li>
                            }

                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Logout"><i class="fa-solid fa-right-from-bracket me-2"></i>Çıkış Yap</a>
                            </li>                       

                        }
                        else
                        {

                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Login"><i class="fa-solid fa-right-to-bracket me-2"></i>Giriş Yap</a>
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Register"><i class="fa-solid fa-user me-2"></i>Üye Ol</a>
                            </li>
                        }


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="c:\users\ysnes\.nuget\packages\ntoastnotify\8.0.0\contentfiles\any\net6.0\wwwroot\noty.js"></script>
    <script src="c:\users\ysnes\.nuget\packages\ntoastnotify\8.0.0\contentfiles\any\net6.0\wwwroot\toastr.js"></script>
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>