WebCoreUI/Controllers/AdminController.cs
using Business.Abstract;
using Entities.Concrete;
using Entities.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Plugins;
using System.Collections.Generic;
using System.Security.Claims;

namespace WebCoreUI.Controllers
{
    [Authorize(Roles = "admin")]
    [Route("[controller]/[action]")]
    public class AdminController : Controller
    {
        IAdminService _adminService;

        public AdminController(IAdminService adminService)
        {
            _adminService = adminService;
        }

        // AdminLayout.cshtml      
        [HttpGet]
        public IActionResult AdminIndex()
        {
            return View();
        }

        //Admin tarafta Müşteriler Listesi
        [HttpGet]
        public IActionResult GetAllCustomer()
        {
            var response = _adminService.GetAllCustomerList();
            return View(response);
        }

        //Admin tarafta Müşterinin Talepleri
        [HttpGet]
        public IActionResult GetRequestListByCustomerId(int customerId)
        {
            ViewBag.CustomerName = _adminService.GetByIdCustomerName(customerId);
            var response = _adminService.GetRequestsByCustomerId(customerId);
            return View(response);
        }

        //Admin tarafta Müşteririnin Taleplerini Asenkron getirme
        //[HttpGet]
        //public async Task<IActionResult> GetRequestListByCustomerIdAsync(int customerId)
        //{
        //    ViewBag.CustomerName = await _adminService.GetByIdCustomerNameAsync(customerId);
        //    var response = _adminService.GetRequestsByCustomerId(customerId);
        //    return View(response);

        //}


        //Admin tarafta MüşteriTemsilcilerini Listeleme
        [HttpGet]
        public IActionResult GetAllCustomerRep()
        {
            var response = _adminService.GetAllCustomerRepList();
            return View(response);
        }

        //Müşteri Temsilcisi Kayıt Ekran Formu
        [AllowAnonymous]
        public IActionResult CreateCustomerRep()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public IActionResult CreateCustomerRep(CustomerRepRegisterDto model)
        {
            if (ModelState.IsValid)
            {
                _adminService.AddCustomerRepDto(model);
                return RedirectToAction(nameof(GetAllCustomerRep));
            }

            ModelState.AddModelError("", "Üye olma işlemi gerçekleşmedi");
            return View(model);
        }

        [HttpGet]
        //[Route("{customerId?}/{customerRepId?}")]
        public IActionResult EditCustomerRep(int customerId)
        {
            CustomerRepEditDto model = _adminService.GetCustomerRepByCustomerId(customerId);

            //ViewBag.CustomerId = customerId;
            //ViewBag.CustomerRepId = customerRepId;

            return View(model);
        }
        [HttpPost]
        //[Route("{customerId?}/{customerRepId?}")]
        public IActionResult EditCustomerRep(CustomerRepEditDto model)
        {
            _adminService.EditCustomerRepDto(model);
            return RedirectToAction(nameof(GetAllCustomerRep));
        }

        [HttpGet]
        public IActionResult DeleteCustomerRep(int customerId)
        {
            _adminService.DeleteCustomerRepDto(customerId);
            return RedirectToAction(nameof(GetAllCustomerRep));
        }

        //Müşteri Temsilcisi Rapor Ekranı
        [HttpGet]
        public IActionResult GetReport()
        {
            ViewBag.AllCompletedRequest = _adminService.GetReportList()[0].AllCompletedRequestCount;
            ViewBag.AllCallTime = _adminService.GetReportList()[0].AllCallTimeTotal;

            return View(_adminService.GetReportList());
        }

        //Müşteri Temsilcisi Belli Tarih aralığındaki Rapor Ekranı
        public IActionResult GetReportByDate()
        {
            return View(new List<ReportByDateDto>());
        }

        //Müşteri Temsilcisi Belli Tarih aralığındaki Rapor Ekranı
        [HttpPost]
        public IActionResult GetReportByDate(DateTime startDate, DateTime endDate)
        {
            ViewBag.StartDate = startDate;  
            ViewBag.EndDate = endDate;
            ViewBag.AllCompletedRequest = _adminService.GetByDateReportList(startDate,endDate)[0].AllCompletedRequestCount;
            ViewBag.AllCallTime = _adminService.GetByDateReportList(startDate,endDate)[0].AllCallTimeTotal;
            var reportList = _adminService.GetByDateReportList(startDate, endDate);
            return View(reportList);
        }

      
    }
}

WebCoreUI/Controllers/RequestController.cs
using Business.Abstract;
using Entities.Concrete;
using Entities.DTOs;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace WebCoreUI.Controllers
{
    public class RequestController : Controller
    {
        IRequestService _requestService;

        public RequestController(IRequestService requestService)
        {
            _requestService = requestService;
        }

        public IActionResult Index()
        {
            return View();
        }

        //Hangi müşteri login olduysa onun Taleplerini gösteren method
        public IActionResult RequestListByCustomerId()
        {
            string emailForClaim = User.FindFirstValue("Email");   
            var response = _requestService.GetRequestByEmail(emailForClaim);

            return View(response);
        }

        //Talep Ekleme Form Ekranı
        public IActionResult RequestCreate()
        {
            ViewBag.RequestTypes = _requestService.GetBySelectListRequestTypes();
            return View("RequestCreateForm", new RequestCreateDto());
        }
        [HttpPost]
        public IActionResult RequestCreate(RequestCreateDto model)
        {
            //Claimdeki Id : 
            int customerId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            
            _requestService.AddRequestCreateDto(model,customerId);
            return RedirectToAction(nameof(RequestListByCustomerId));
        }

        //Bütün Taleplerin Listesi
        public IActionResult RequestList()
        {
            var response = _requestService.GetAllRequestList();
            return View(response);
        }

        //Müşteri Temsilcisinin Talebi Aldığı Method
        //Talep Detay sayfasına geçer 
        public IActionResult RequestCheckByCustomerRep(int requestId)
        {
            string emailForClaim = User.FindFirstValue("Email");
            ViewBag.RequestId = requestId;

            var response = _requestService.RequestDetailByCustomerRep(requestId, emailForClaim);
            return View("RequestDetailForm", response);
           
        }
       
        //Kapanan Talepleri Listeleyen method
         public IActionResult RequestCompletedList()
        {
            var response = _requestService.GetRequestCompletedList();
            return View(response);
        }

        //Yeni açılan Talepleri Listeleyen method
        public IActionResult RequestNewList()
        {
            var response = _requestService.GetRequestNewList();
            return View(response);
        }

        //Değerlendirmede olan Talepleri Listeleyen method
        public IActionResult RequestContinueList()
        {
            var response = _requestService.GetRequestContinueList();
            return View(response);
        }

       
        //Müşteri Temsilcisinin çözdüğü Taleplerin Listesi
        public IActionResult CustomerRepRequestCompletedList()
        {
            string emailForClaim = User.FindFirstValue("Email");
            ViewBag.CustomerRepEmail=emailForClaim;
            var response = _requestService.GetCustomerRepRequestCompletedList(emailForClaim);
            return View(response);
        }

    }
}

WebCoreUI/Views/Admin/AdminIndex.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="text-center">
    <h3 class="display-4">YÖNETİM SAYFASI</h3>

</div>

<nav class="navbar navbar-expand-lg navbar-dark b" style="background-color: #e3f2fd;">

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fa-solid fa-code-pull-request"></i> Talepler
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li>
                        <a class="dropdown-item" asp-controller="Request" asp-action="RequestList"><i class="fa-solid fa-list"></i> Bütün Müşteri Talepleri</a>
                    </li>
                    <li>
                        <a class="dropdown-item" asp-controller="Request" asp-action="RequestNewList"><i class="fa-solid fa-plus"></i> Yeni Açılan Talepler</a>
                    </li>
                    <li>
                        <a class="dropdown-item" asp-controller="Request" asp-action="RequestContinueList"><i class="fa-solid fa-up-right-from-square"></i> Değerlendirmede olan Talepler</a>
                    </li>
                    <li>
                        <a class="dropdown-item" asp-controller="Request" asp-action="RequestCompletedList"><i class="fa-solid fa-check"></i> Kapanan Talepler</a>
                    </li>
                </ul>
            </li>

            <li class="nav-item active">
                <a class="nav-link text-dark" asp-controller="Admin" asp-action="GetAllCustomer"><i class="fa-solid fa-users"></i> Müşteriler</a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fa-solid fa-user-group"></i> Müşteri Temsilcileri
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li>
                        <a class="dropdown-item" asp-controller="Admin" asp-action="GetAllCustomerRep"><i class="fa-solid fa-user-group"></i> Müşteri Temsilcileri</a>
                    </li>   
                    <li>
                        <a class="dropdown-item" asp-controller="Admin" asp-action="CreateCustomerRep"><i class="fa-solid fa-plus"></i> Müşteri Temsilcileri Kayıt</a>
                    </li>
                </ul>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fa-solid fa-chart-line"></i> Raporlar
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li class="nav-item active">
                        <a class="nav-link text-dark" asp-controller="Admin" asp-action="GetReport"><i class="fa-solid fa-chart-simple"></i> Raporlar</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link text-dark" asp-controller="Admin" asp-action="GetReportByDate"><i class="fa-solid fa-calendar-days"></i> Tarih Aralıklı Raporlar</a>
                    </li>
                </ul>
            </li>

           

        </ul>
    </div>
</nav>

WebCoreUI/Views/Admin/CreateCustomerRep.cshtml
@model Entities.DTOs.CustomerRepRegisterDto

@{
    ViewData["Title"] = "Müşteri Temsilcisi Kayıt Ekranı";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-4">
            <div class="card shadow-lg">
                <div class="card-body">
                    <h3 class="card-title text-center">@ViewData["Title"]</h3>
                    <hr />
                    <form method="post">

                        <div asp-validation-summary="ModelOnly" class="text-danger small"></div>

                        <div class="form-group mb-3">
                            <label asp-for="FirstName" class="form-label">Ad</label>
                            <input asp-for="FirstName" class="form-control" />
                            <span asp-validation-for="FirstName" class="text-danger small"></span>
                        </div>
                        <div class="form-group mb-3">
                            <label asp-for="LastName" class="form-label">Soyad</label>
                            <input asp-for="LastName" class="form-control" />
                            <span asp-validation-for="FirstName" class="text-danger small"></span>
                        </div>
                        <div class="form-group mb-3">
                            <label asp-for="Email" class="form-label">Mail</label>
                            <input asp-for="Email" class="form-control" placeholder="Mail..." />
                            <span asp-validation-for="Email" class="text-danger small"></span>
                        </div>
                        <div class="form-group mb-3">
                            <label asp-for="Phone" class="form-label">TelNo</label>
                            <input asp-for="Phone" class="form-control" placeholder="Tel..." />
                            <span asp-validation-for="Phone" class="text-danger small"></span>
                        </div>

                        <div class="form-group mb-3">
                            <label asp-for="Password" class="form-label">Parola</label>
                            <input asp-for="Password" class="form-control" type="password" placeholder="P@ssW0rd!" />
                            <span asp-validation-for="Password" class="text-danger small"></span>
                        </div>

                        <div class="form-group mb-3">
                            <label asp-for="RePassword" class="form-label">Parola Tekrar</label>
                            <input asp-for="RePassword" class="form-control" type="password" placeholder="P@ssW0rd!" />
                            <span asp-validation-for="RePassword" class="text-danger small"></span>
                        </div>

                        <div class="form-group d-grid mb-3">
                            @* d-grid butonun bulunduğu dive yayılmasını sağlar*@
                            <button type="submit" class="btn btn-primary d-block"><i class="fa-solid fa-paper-plane me-2"></i>Kaydet</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
 }

WebCoreUI/Views/Admin/EditCustomerRep.cshtml
@model Entities.DTOs.CustomerRepEditDto

@{
    ViewData["Title"] = "Müşteri Temsilcisi Kayıt Ekranı";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-4">
            <div class="card shadow-lg">
                <div class="card-body">
                    <h3 class="card-title text-center">@ViewData["Title"]</h3>
                    <hr />
                    <form asp-action="EditCustomerRep" asp-controller="Admin" data-val="true" method="post">

                        <div asp-validation-summary="ModelOnly" class="text-danger small"></div>

                        <div class="form-group mb-3">
                            <label asp-for="FirstName" class="form-label">Ad</label>
                            <input asp-for="FirstName" class="form-control" />
                            <span asp-validation-for="FirstName" class="text-danger small"></span>
                        </div>
                        <div class="form-group mb-3">
                            <label asp-for="LastName" class="form-label">Soyad</label>
                            <input asp-for="LastName" class="form-control" />
                            <span asp-validation-for="FirstName" class="text-danger small"></span>
                        </div>
                        <div class="form-group mb-3">
                            <label asp-for="Email" class="form-label">Mail</label>
                            <input asp-for="Email" class="form-control" placeholder="Mail..." />
                            <span asp-validation-for="Email" class="text-danger small"></span>
                        </div>
                        <div class="form-group mb-3">
                            <label asp-for="Phone" class="form-label">TelNo</label>
                            <input asp-for="Phone" class="form-control" placeholder="Tel..." />
                            <span asp-validation-for="Phone" class="text-danger small"></span>
                        </div>

                        <div class="form-group mb-3">
                            <label asp-for="Password" class="form-label">Parola</label>
                            <input asp-for="Password" class="form-control" type="password" placeholder="P@ssW0rd!" />
                            <span asp-validation-for="Password" class="text-danger small"></span>
                        </div>

                        <div class="form-group mb-3">
                            <label asp-for="RePassword" class="form-label">Parola Tekrar</label>
                            <input asp-for="RePassword" class="form-control" type="password" placeholder="P@ssW0rd!" />
                            <span asp-validation-for="RePassword" class="text-danger small"></span>
                        </div>

                        <input type="hidden" asp-for="CustomerId" value="@Model.CustomerId" />
                        <input type="hidden" asp-for="CustomerRepId" value="@Model.CustomerRepId" />

                        <div class="form-group d-grid mb-3">
                            <button type="submit" asp-route-customerId="@Model.CustomerId" class="btn btn-primary d-block"><i class="fa-solid fa-paper-plane me-2"></i>Güncelle</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
 }

WebCoreUI/Views/Admin/GetAllCustomer.cshtml
@model List<Entities.DTOs.CustomerAllListDto>

@{
    ViewData["Title"] = "BÜTÜN MÜŞTERİLER";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <div class="row mt-3 mb-3">
        <div class="col-12 text-center">
            <h1 class="display-4">@ViewData["Title"]</h1>
        </div>
    </div>


    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Müşteri Ad</th>
                                <th>Soyad</th>
                                <th>Mail</th>
                                <th>Parola</th>
                                <th>Telefon</th>
                                <th>Rolü</th>
                                <th>  </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.FirstName</td>
                                    <td>@item.LastName</td>
                                    <td>@item.Email</td>
                                    <td>@item.Password</td>
                                    <td>@item.Phone</td>
                                    <td>@item.Role</td>
                                    <td>
                                        <a asp-action="GetRequestListByCustomerId" asp-controller="Admin" asp-route-id="@item.CustomerId" class="btn btn-primary"><i class="fa-regular fa-file-lines"></i> Talepleri</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

WebCoreUI/Views/Admin/GetAllCustomerRep.cshtml
@model List<Entities.DTOs.CustomerRepAllListDto>

@{
    ViewData["Title"] = "BÜTÜN MÜŞTERİ TEMSİLCİLERİ";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <div class="row mt-3 mb-3">
        <div class="col-12 text-center">
            <h1 class="display-4">@ViewData["Title"]</h1>
        </div>
    </div>

    <a asp-action="CreateCustomerRep" asp-controller="Admin" class="btn btn-danger">Yeni Müşteri Temsilcisi</a>


    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Müşteri Temsilcisi Ad</th>
                                <th>Soyad</th>
                                <th>Mail</th>
                                <th>Parola</th>
                                <th>Telefon</th>
                                <th>Rolü</th>
                                <th> </th>
                                <th> </th>
                               
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.FirstName</td>
                                    <td>@item.LastName</td>
                                    <td>@item.Email</td>
                                    <td>@item.Password</td>
                                    <td>@item.Phone</td>
                                    <td>@item.Role</td>

                                    <td><a asp-action="EditCustomerRep" asp-controller="Admin" asp-route-customerId="@item.CustomerId" asp-route-customerRepId="@item.CustomerRepId" class="btn btn-warning">Güncelle</a></td>
                                    <td><a asp-action="DeleteCustomerRep" asp-controller="Admin" asp-route-customerId="@item.CustomerId" asp-route-customerRepId="@item.CustomerRepId" class="btn btn-success">Sil</a></td>

                                    @*href="/Admin/EditCustomerRep/@item.CustomerId/@item.CustomerRepId"*@
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

WebCoreUI/Views/Admin/GetReport.cshtml
@model List<Entities.DTOs.ReportDto>

@{
    ViewData["Title"] = "MÜŞTERİ TEMSİLCİLERİ RAPORLARI";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <div class="row mt-3 mb-3">
        <div class="col-12 text-center">
            <h1 class="display-4">@ViewData["Title"]</h1>
        </div>
    </div>



    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Ad</th>
                                <th>Soyad</th>
                                <th>Mail</th>
                                <th>Çözülen Talep Sayısı</th>
                                <th>Toplam Cevaplanma Süresi(dk cinsinden)</th>
                              @*<th>Bütün Çözülen Taleplerin Sayısı </th>
                                <th>Bütün Taleplerin Toplam Cevaplanma Süresi(dk cinsinden) </th>*@
                                <th>Ortalama Çözülen Talep Sayısı % </th>
                                <th>Ortalama Cevaplanma Süresi % </th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.FirstName</td>
                                    <td>@item.LastName</td>
                                    <td>@item.Email</td>
                                    <td>@item.CompletedRequestCount</td>
                                    <td>@item.CallTimeTotal</td>
                                  @*<td>@item.AllCompletedRequestCount</td>
                                    <td>@item.AllCallTimeTotal</td>*@
                                    <td>@item.AverageCompletedRequestCount</td>
                                    <td>@item.AverageCallTimeTotal</td>

                                </tr>                            
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

   
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <div class="col-6">
                            <label> Toplam Çözülen Talep Sayısı : @ViewBag.AllCompletedRequest </label>
                          

                        </div>
                        <div class="col-6">
                            <label> Talebin Toplam Cevaplanma Süresi : @ViewBag.AllCallTime dakika </label>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>

WebCoreUI/Views/Admin/GetReportByDate.cshtml
@using Entities.DTOs
@model List<Entities.DTOs.ReportByDateDto>

@{
    ViewData["Title"] = "MÜŞTERİ TEMSİLCİLERİ RAPORLARI";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <div class="row mt-3 mb-3">
        <div class="col-12 text-center">
            <h1 class="display-4">@ViewData["Title"]</h1>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Tarih Aralığı Seç</h5>
            <form asp-action="GetReportByDate" asp-controller="Admin" data-val="true" method="post">
                <div class="form-group row">
                    <div class="col-md-6">
                        <label for="StartDate">Başlangıç Tarihi</label>                     
                        <input name="StartDate" type="date" class="form-control" />
                    </div>
                    <div class="col-md-6">
                        <label for="EndDate">Bitiş Tarihi</label>
                        <input name="endDate" type="date" class="form-control" />
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-12 text-end">
                        <button class="btn btn-secondary" type="submit"><i class="fa-solid fa-chart-line"></i>  Göster</button>
                    </div>
                </div>

            </form>
        </div>
    </div>

    <div class="row">
        <span> @ViewBag.StartDate?.ToString("dd MMMM yyyy") - @ViewBag.EndDate?.ToString("dd MMMM yyyy")  Tarihleri arasındaki Rapor</span>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th> Ad</th>
                                <th>Soyad</th>
                                <th>Mail</th>
                                <th>Çözülen Talep Sayısı</th>
                                <th>Toplam Cevaplanma Süresi(dk cinsinden)</th>
                              @*<th>Bütün Çözülen Taleplerin Sayısı </th>
                                <th>Bütün Taleplerin Toplam Cevaplanma Süresi(dk cinsinden) </th>*@
                                <th>Ortalama Çözülen Talep Sayısı % </th>
                                <th>Ortalama Cevaplanma Süresi % </th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.FirstName</td>
                                    <td>@item.LastName</td>
                                    <td>@item.Email</td>
                                    <td>@item.CompletedRequestCount</td>
                                    <td>@item.CallTimeTotal</td>
                                    @*<td>@item.AllCompletedRequestCount</td>
                                    <td>@item.AllCallTimeTotal</td>*@
                                    <td>@item.AverageCompletedRequestCount</td>
                                    <td>@item.AverageCallTimeTotal</td>

                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

   
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <div class="col-6">
                            <label> Bu Tarihler arasında Toplam Çözülen Talep Sayısı : @ViewBag.AllCompletedRequest </label>


                        </div>
                        <div class="col-6">
                            <label> Bu Tarihler arasında Talebin Toplam Cevaplanma Süresi : @ViewBag.AllCallTime dakika </label>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>

WebCoreUI/Views/Admin/GetRequestListByCustomerIdAsync.cshtml
@model List<Entities.DTOs.RequestListByCustomerDto>

@{
    ViewData["Title"] = "MÜŞTERİNİN TALEPLERİ";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <div class="row mt-3 mb-3">
        <div class="col-12 text-center">
            <h1 class="display-4"> @ViewBag.CustomerName @ViewData["Title"]</h1>
        </div>
    </div>


    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Talep Tarihi</th>
                                <th>Talep</th>
                                <th>Talep Türü</th>
                                <th>Durum</th>
                                <th>Müşteri Temsilcisi</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.CreateDate.ToString("dd MMMM yyyy")</td>
                                    <td>@item.Description</td>
                                    <td>@item.RequestTypeName</td>
                                    <td>@item.StatusName</td>
                                    <td>@item.CustomerRepName</td>

                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>